# Generated by Django 2.2.4 on 2019-09-01 14:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20190901_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_caption',
            field=tinymce.models.HTMLField(),
        ),
    ]
